easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\CasClinique
        - App\Entity\Categorie
        - App\Entity\ChampsClinique        
        - App\Entity\Questions
        - App\Entity\Reponses
        - App\Entity\Roles
        - App\Entity\Score
        - App\Entity\SousCategorie        
        - App\Entity\TestVideo
        - App\Entity\User
