easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\CasClinique
        - App\Entity\Categorie
        - App\Entity\ChampsClinique
        - App\Entity\Hypotheses
        - App\Entity\Questions
        - App\Entity\Reponses
        - App\Entity\Roles
        - App\Entity\Test
        - App\Entity\TestSpe
        - App\Entity\Users
